server:
  port: 8080
  servlet:
    context-path: /application
  tomcat:
    accesslog:
      enabled: true
spring:
  liquibase:
    change-log: db/changelog/master.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5432/template"
    password: London8793
    username: postgres
