INSERT INTO users (email, createdat)
VALUES ('email1@one.ru', current_timestamp),
       ('email2@one.ru', current_timestamp),
       ('email3@one.ru', current_timestamp),
       ('email4@one.ru', current_timestamp),
       ('email5@one.ru', current_timestamp),
       ('email6@one.ru', current_timestamp),
       ('email7@one.ru', current_timestamp),
       ('email8@one.ru', current_timestamp),
       ('email9@one.ru', current_timestamp),
       ('email10@one.ru', current_timestamp),
       ('email11@one.ru', current_timestamp),
       ('email12@one.ru', current_timestamp),
       ('email13@one.ru', current_timestamp),
       ('email14@one.ru', current_timestamp),
       ('email15@one.ru', current_timestamp),
       ('email16@one.ru', current_timestamp),
       ('email17@one.ru', current_timestamp),
       ('email18@one.ru', current_timestamp),
       ('email19@one.ru', current_timestamp),
       ('email20@one.ru', current_timestamp)